### ISSUE TITLE
Only ID comes back as data for all values

### ISSUE THREAD

**Issue by druby-luke** [ernestre/Symfony-FOSUserBundle-HWIOAuthBundle#4]
Thanks for this awesome git, but there is a small issue im trying to sort out.

The data that is available and being used is only the ID. Name, email ect. are not being passed along. Twig session dump doesnt reveal anny other information either. Anny tips?

**Comment by ernestre** [comment]
By default, you only get the `id` from the provider. In order to get more data you have to specify which data you need. [For example.](https://github.com/ernestre/Symfony-FOSUserBundle-HWIOAuthBundle/issues/1#issuecomment-220789797)

Also, you have to change [these lines](https://github.com/ernestre/Symfony-FOSUserBundle-HWIOAuthBundle/blob/master/src/AppBundle/Security/Core/User/FOSUBUserProvider.php#L50-L54) according to your requirements to save the data returned by the provider.

**Comment by druby-luke** [comment]
Thanks 👍  I now have useful data in my database. Only thing (because im fairly new to symfony) the provider gets all information from in my case Google. Thing is when developing the username within symfony is set to id. so the scope has the information needed but symfony uses the ID as if it is a username, could you show me where the username is set?.

My scope includes: 

`            scope:               "https://www.googleapis.com/auth/plus.login https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile"
`

**Comment by druby-luke** [comment]
nevermind! got it all figured out! Thanks 👍
